resources:
  repositories:
    - repository: ci_cd
      type: github
      name: original-decisions/ci-cd
      endpoint: original-decisions

pr:
- master/src
- master/tests

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- powershell: |
   git clone https://github.com/original-decisions/ci-cd -v --progress;
   
   dir;
  errorActionPreference: silentlyContinue
  workingDirectory: '$(Build.Repository.LocalPath)'
  displayName: 'clone ci scripts'
- template: AzureDevOps_(VSTS)/templates/netcoreapp_pr_ps.yml@ci_cd

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     **/*.nupkg
     **/*test*.xml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: YodLabs.VariableTasks.AddTag.AddTag@0
  displayName: 'Add Tag(s) on Succeeded build'
  inputs:
    tags: |
     Order Processing
     Core
     Succeeded