//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odec.CP.Server.Model.OrderProcessing.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderProcessingScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal OrderProcessingScripts() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odec.CP.Server.Model.OrderProcessing.Migrations.OrderProcessingScripts", typeof(OrderProcessingScripts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  begin tran
        ///IF schema_id(&apos;ecash&apos;) IS NULL
        ///    EXECUTE(&apos;CREATE SCHEMA [ecash]&apos;)
        ///IF  NOT EXISTS (SELECT * FROM sys.objects 
        ///WHERE object_id = OBJECT_ID(N&apos;[ecash].[AccountOperationHistory]&apos;) AND type in (N&apos;U&apos;))
        ///begin
        ///CREATE TABLE [ecash].[AccountOperationHistory] (
        ///    [UserId] [int] NOT NULL,
        ///    [OperationDate] [datetime] NOT NULL,
        ///    [MoneyTransfered] [decimal](18, 2) NOT NULL,
        ///    [OperationTypeId] [int] NOT NULL,
        ///    CONSTRAINT [PK_ecash.AccountOperationHistory] PRIMARY KEY ([UserId], [Operatio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MoneyInitial {
            get {
                return ResourceManager.GetString("MoneyInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  begin tran
        ///if not exists( select top 1 1 from ecash.OperationTypes where code like &apos;CASHDEPOSIT&apos;)
        ///begin
        ///INSERT INTO ecash.OperationTypes (Name,Code,IsActive,SortOrder,DateCreated,DateUpdated)
        ///values (&apos;Cash Deposit&apos;,&apos;CASHDEPOSIT&apos;,1,0,GetDate(),GetDate())
        ///end
        ///if not exists( select top 1 1 from ecash.OperationTypes where code like &apos;USERTOUSERTRANSFER&apos;)
        ///begin
        ///INSERT INTO ecash.OperationTypes (Name,Code,IsActive,SortOrder,DateCreated,DateUpdated)
        ///values (&apos;User To User Transfer&apos;,&apos;USERTOUSERTRANSFER&apos;,1,0, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MoneyInitialSeed {
            get {
                return ResourceManager.GetString("MoneyInitialSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  begin tran
        ///IF schema_id(&apos;order&apos;) IS NULL
        ///    EXECUTE(&apos;CREATE SCHEMA [order]&apos;)
        ///
        ///IF  NOT EXISTS (SELECT * FROM sys.objects 
        ///	WHERE object_id = OBJECT_ID(N&apos;[order].[DeliveryCharges]&apos;) AND type in (N&apos;U&apos;))
        ///begin
        ///	CREATE TABLE [order].[DeliveryCharges] (
        ///    [ZoneId] [int] NOT NULL,
        ///    [DeliveryMethodId] [int] NOT NULL,
        ///    [ChargeValue] [decimal](18, 2) NOT NULL,
        ///    CONSTRAINT [PK_order.DeliveryCharges] PRIMARY KEY ([ZoneId], [DeliveryMethodId])
        ///	)
        ///	CREATE INDEX [IX_ZoneId] ON [order].[DeliveryCha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderCtxInitial {
            get {
                return ResourceManager.GetString("OrderCtxInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  begin tran
        ///if not exists( select top 1 1 from dbo.Sexes where code like &apos;NOSEX&apos;)
        ///begin
        ///INSERT INTO dbo.Sexes (Name,Code,IsActive,SortOrder,DateCreated,DateUpdated)
        ///values (&apos;No sex selected&apos;,&apos;NOSEX&apos;,1,0,GetDate(),GetDate())
        ///end
        ///if not exists( select top 1 1 from [order].DeliveryMethods where code like &apos;ELECTRONIC&apos;)
        ///begin
        ///INSERT INTO [order].DeliveryMethods (Name,Code,IsActive,SortOrder,DateCreated,DateUpdated,[Description])
        ///values (&apos;Electronic delivery&apos;,&apos;ELECTRONIC&apos;,0,0,GetDate(),GetDate(),&apos;&apos;)
        ///end        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderInitialSeed {
            get {
                return ResourceManager.GetString("OrderInitialSeed", resourceCulture);
            }
        }
    }
}
